version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "download-to-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ogt3rjnvqnpx"
s3_prefix = "download-to-s3"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
