AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  download-to-s3

  Download a file, upload to S3, and return a presigned URL.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      EndpointConfiguration:
        Type: REGIONAL
      Domain:
        DomainName: api.rophy.online
        CertificateArn: arn:aws:acm:ap-northeast-1:572921885201:certificate/cfc17c2d-d8e9-40e4-9e85-d10124c73919
        EndpointConfiguration: REGIONAL
        BasePath:
          - downloader
  DownloadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: index.createJob
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        Download:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref ApiGateway
      Environment:
        Variables:
          BUCKET: ***REMOVED***
          PREFIX: shared
#          CORS_ALLOW_ORIGIN: "'*'"

Outputs:
  WebApi:
    Description: "API Gateway endpoint URL for Prod stage the function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/download-to-s3/"
  DownloadFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt DownloadFunction.Arn
  DownloadFunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt DownloadFunctionRole.Arn
